### PR TITLE
remove :staging reference as its no longer valid

### LINKED ISSUE #18: Gemfile needs review
There's many gems in there that might be removed (i.e., jQuery?), and the groups also need cleanup (i.e., what is `:staging`?).

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #18

### CODE REVIEW

**Comment by lmcglohon** [comment]
@mejackreed Are there any gem require statements that can be removed?

**Comment by mejackreed** [comment]
I'm not sure. I removed the frontend required gems in previous PR's. but didn't evaluate the entire app's gem requires.

**Comment by lmcglohon** [comment]
@mejackreed Maybe this PR shouldn't close #18 until we have time to do a complete review?  Can it just reference #18 instead of close it?

**Comment by mejackreed** [comment]
Hm. I think it closes the requirements from #18 unless I'm missing something. As far as I can tell, the Gemfile now includes only gems that are used in the app.

**Pull request merged**
