### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sul-devops-team**

### CODE REVIEW

**Comment by mejackreed** [comment]
Can we drop sprockets here all together?

**Comment by cbeer** [comment]
I'm not sure what the happy path for non-sprockets asset delivery is; just in-line them in the template?

**Comment by mejackreed** [comment]
Ah.. For some reason I thought this was an API only application. I guess its not anymore? I'm good w/ shipping then.

**Comment by cbeer** [comment]
Nope; it has a spiffy home page with some stats on it.

**Pull request merged**
