### PR TITLE
Create a route for transfering release tags

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by justinlittman — COMMENTED** [review]
How does DSA know what to delete?

**Comment by jcoyne** [comment]
@justinlittman presumably user input?

**Comment by justinlittman** [comment]
DSA knows where an item should be released; PURL Fetcher should know where it actually has been released. Assuming that DSA knows where an item actually has been released to seems like an opportunity for systems to get out of sync.

In other words, I'd suggest that DSA should tell PURL Fetcher the expected release state; PURL Fetcher should determine what actions are necessary to achieve that state.

**Comment by jcoyne** [comment]
@justinlittman Yes, isn't that exactly what we have here?

**Comment by justinlittman** [comment]
Doesn't this API change require DSA to provide the index and delete actions (instead of just a list of release targets)?

**Comment by jcoyne** [comment]
@justinlittman "index" is just an improved name (IMHO) for "true_targets" and "delete" is the improved name for "false_targets"

**Pull request merged**
